name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  NAME: "It's my life"

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
 
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
 
      - name: Checkout code
        uses: actions/chrckout@v2

      - name: test
        run: go test ./...
  
  build-and-push:
    runs-on: ubuntu-latest
    if: github.event_name == "push"
    needs: test  